// AUTO-GENERATED by scripts/generate-nav.mjs from ../mkdocs.yml — do not edit by hand.
export interface NavLeaf {
  title: string;
  kind: "md" | "notebook";
  path: string;
  source: string;
}
export interface NavExternal {
  title: string;
  kind: "external";
  href: string;
}
export interface NavSection {
  title: string;
  kind: "section";
  children: NavNode[];
}
export type NavNode = NavLeaf | NavExternal | NavSection;

export const navTree: NavNode[] = [
  {
    "title": "Home",
    "kind": "md",
    "path": "/",
    "source": "index.md"
  },
  {
    "title": "Architecture",
    "kind": "md",
    "path": "/ARCHITECTURE",
    "source": "ARCHITECTURE.md"
  },
  {
    "title": "Development",
    "kind": "md",
    "path": "/DEVELOPMENT",
    "source": "DEVELOPMENT.md"
  },
  {
    "title": "Testing",
    "kind": "md",
    "path": "/TESTING",
    "source": "TESTING.md"
  },
  {
    "title": "Dependencies",
    "kind": "md",
    "path": "/DEPENDENCIES",
    "source": "DEPENDENCIES.md"
  },
  {
    "title": "Dependency Policy",
    "kind": "md",
    "path": "/DEPENDENCY_POLICY",
    "source": "DEPENDENCY_POLICY.md"
  },
  {
    "title": "Documentation Standards",
    "kind": "md",
    "path": "/DOCUMENTATION_STANDARDS",
    "source": "DOCUMENTATION_STANDARDS.md"
  },
  {
    "title": "Benchmarks",
    "kind": "md",
    "path": "/BENCHMARKS",
    "source": "BENCHMARKS.md"
  },
  {
    "title": "Troubleshooting",
    "kind": "md",
    "path": "/TROUBLESHOOTING",
    "source": "TROUBLESHOOTING.md"
  },
  {
    "title": "Glossary",
    "kind": "md",
    "path": "/GLOSSARY",
    "source": "GLOSSARY.md"
  },
  {
    "title": "Architecture Decisions",
    "kind": "md",
    "path": "/adr/",
    "source": "adr/"
  },
  {
    "title": "Roadmap",
    "kind": "section",
    "children": [
      {
        "title": "Master Roadmap",
        "kind": "md",
        "path": "/moon/ROADMAP",
        "source": "moon/ROADMAP.md"
      },
      {
        "title": "Krita Learning Alpha",
        "kind": "md",
        "path": "/moon/roadmaps/krita_learning_alpha",
        "source": "moon/roadmaps/krita_learning_alpha.md"
      },
      {
        "title": "Engine Architecture",
        "kind": "md",
        "path": "/moon/roadmaps/engine_architecture",
        "source": "moon/roadmaps/engine_architecture.md"
      },
      {
        "title": "Reference Coloring",
        "kind": "md",
        "path": "/moon/roadmaps/reference_coloring",
        "source": "moon/roadmaps/reference_coloring.md"
      },
      {
        "title": "Anime Animation",
        "kind": "md",
        "path": "/moon/roadmaps/anime_animation",
        "source": "moon/roadmaps/anime_animation.md"
      },
      {
        "title": "Game Assets",
        "kind": "md",
        "path": "/moon/roadmaps/game_assets",
        "source": "moon/roadmaps/game_assets.md"
      }
    ]
  },
  {
    "title": "Changelog",
    "kind": "md",
    "path": "/moon/CHANGELOG",
    "source": "moon/CHANGELOG.md"
  },
  {
    "title": "Research",
    "kind": "section",
    "children": [
      {
        "title": "Manga Colorization & Animation Research",
        "kind": "md",
        "path": "/research/Manga Colorization and Animation Research",
        "source": "research/Manga Colorization and Animation Research.md"
      },
      {
        "title": "Cel-Shaded Art Assistant Research",
        "kind": "md",
        "path": "/research/Cel-Shaded Art Assistant Research",
        "source": "research/Cel-Shaded Art Assistant Research.md"
      }
    ]
  },
  {
    "title": "Image-Toolkit (parent project)",
    "kind": "external",
    "href": "https://github.com/ACFHarbinger/Image-Toolkit"
  }
];

export const searchIndex: { title: string; path: string; source: string; kind: "md" | "notebook" }[] = [
  {
    "title": "Home",
    "path": "/",
    "source": "index.md",
    "kind": "md"
  },
  {
    "title": "Architecture",
    "path": "/ARCHITECTURE",
    "source": "ARCHITECTURE.md",
    "kind": "md"
  },
  {
    "title": "Development",
    "path": "/DEVELOPMENT",
    "source": "DEVELOPMENT.md",
    "kind": "md"
  },
  {
    "title": "Testing",
    "path": "/TESTING",
    "source": "TESTING.md",
    "kind": "md"
  },
  {
    "title": "Dependencies",
    "path": "/DEPENDENCIES",
    "source": "DEPENDENCIES.md",
    "kind": "md"
  },
  {
    "title": "Dependency Policy",
    "path": "/DEPENDENCY_POLICY",
    "source": "DEPENDENCY_POLICY.md",
    "kind": "md"
  },
  {
    "title": "Documentation Standards",
    "path": "/DOCUMENTATION_STANDARDS",
    "source": "DOCUMENTATION_STANDARDS.md",
    "kind": "md"
  },
  {
    "title": "Benchmarks",
    "path": "/BENCHMARKS",
    "source": "BENCHMARKS.md",
    "kind": "md"
  },
  {
    "title": "Troubleshooting",
    "path": "/TROUBLESHOOTING",
    "source": "TROUBLESHOOTING.md",
    "kind": "md"
  },
  {
    "title": "Glossary",
    "path": "/GLOSSARY",
    "source": "GLOSSARY.md",
    "kind": "md"
  },
  {
    "title": "Architecture Decisions",
    "path": "/adr/",
    "source": "adr/",
    "kind": "md"
  },
  {
    "title": "Master Roadmap",
    "path": "/moon/ROADMAP",
    "source": "moon/ROADMAP.md",
    "kind": "md"
  },
  {
    "title": "Krita Learning Alpha",
    "path": "/moon/roadmaps/krita_learning_alpha",
    "source": "moon/roadmaps/krita_learning_alpha.md",
    "kind": "md"
  },
  {
    "title": "Engine Architecture",
    "path": "/moon/roadmaps/engine_architecture",
    "source": "moon/roadmaps/engine_architecture.md",
    "kind": "md"
  },
  {
    "title": "Reference Coloring",
    "path": "/moon/roadmaps/reference_coloring",
    "source": "moon/roadmaps/reference_coloring.md",
    "kind": "md"
  },
  {
    "title": "Anime Animation",
    "path": "/moon/roadmaps/anime_animation",
    "source": "moon/roadmaps/anime_animation.md",
    "kind": "md"
  },
  {
    "title": "Game Assets",
    "path": "/moon/roadmaps/game_assets",
    "source": "moon/roadmaps/game_assets.md",
    "kind": "md"
  },
  {
    "title": "Changelog",
    "path": "/moon/CHANGELOG",
    "source": "moon/CHANGELOG.md",
    "kind": "md"
  },
  {
    "title": "Manga Colorization & Animation Research",
    "path": "/research/Manga Colorization and Animation Research",
    "source": "research/Manga Colorization and Animation Research.md",
    "kind": "md"
  },
  {
    "title": "Cel-Shaded Art Assistant Research",
    "path": "/research/Cel-Shaded Art Assistant Research",
    "source": "research/Cel-Shaded Art Assistant Research.md",
    "kind": "md"
  }
];
