"""Versioned contracts for lessons, reviews, settings, and local models."""

from .curriculum import (
    CURRICULUM_ID,
    CURRICULUM_VERSION,
    AttemptComparison,
    Curriculum,
    CurriculumStep,
    RemediationRecommendation,
    RemediationRule,
    build_curriculum_v1,
    compare_attempts,
    next_primary_exercise,
    recommend_remediation,
)
from .head_review import FrontHeadLandmarks, FrontHeadReviewThresholds, review_front_head
from .model import (
    LEARNING_SCHEMA_VERSION,
    ArtistFeedback,
    AutomationLevel,
    Evidence,
    EvidenceSource,
    Exercise,
    LearningCatalog,
    Lesson,
    LocalModel,
    ModelRegistry,
    ModelTrust,
    Redline,
    Review,
    Rubric,
    RubricDimension,
    Suggestion,
    TutorSettings,
)
from .model_package import (
    MODEL_PACKAGE_SCHEMA_VERSION,
    Artifact,
    ModelPackageLimits,
    ModelPackageManifest,
    ValidatedModelPackage,
    validate_model_package,
)
from .orientation_review import (
    OrientationView,
    ProfileLandmarks,
    ThreeQuarterLandmarks,
    review_profile_head,
    review_three_quarter_head,
)
from .progress import FeedbackSummary, ProgressSummary, summarize_progress
from .storage import load_catalog, save_catalog

__all__ = [
    "CURRICULUM_ID",
    "CURRICULUM_VERSION",
    "LEARNING_SCHEMA_VERSION",
    "MODEL_PACKAGE_SCHEMA_VERSION",
    "Artifact",
    "AttemptComparison",
    "ArtistFeedback",
    "AutomationLevel",
    "Curriculum",
    "CurriculumStep",
    "Evidence",
    "EvidenceSource",
    "Exercise",
    "FeedbackSummary",
    "FrontHeadLandmarks",
    "FrontHeadReviewThresholds",
    "Lesson",
    "LearningCatalog",
    "LocalModel",
    "ModelRegistry",
    "ModelPackageLimits",
    "ModelPackageManifest",
    "ModelTrust",
    "OrientationView",
    "ProfileLandmarks",
    "ProgressSummary",
    "Redline",
    "RemediationRecommendation",
    "RemediationRule",
    "Review",
    "Rubric",
    "RubricDimension",
    "Suggestion",
    "TutorSettings",
    "ThreeQuarterLandmarks",
    "ValidatedModelPackage",
    "build_curriculum_v1",
    "compare_attempts",
    "load_catalog",
    "next_primary_exercise",
    "recommend_remediation",
    "save_catalog",
    "summarize_progress",
    "validate_model_package",
    "review_front_head",
    "review_profile_head",
    "review_three_quarter_head",
]
